import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { prefix } from "../utils/prefix";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <a href="https://www.google.com" className={styles.card}>
            <h2>test</h2>
            <p>test test</p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
